replicaCount: 1
image:
  repository: your-registry/splunk-port-integration
  tag: latest
  pullPolicy: Always

ocean:
  portClientId: ""
  portClientSecret: ""
  portBaseUrl: "https://api.getport.io"

splunk:
  baseUrl: ""
  tokenSecretName: "splunk-credentials"
  tokenSecretKey: "token"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80